%YAML 1.2
# Copyright (c) 2022, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
---
name: memory_pool
components:
- name: unbounded_allocator
  type: nvidia::gxf::UnboundedAllocator
---
#############
# Pose Tree #
#############
name: global_pose_tree
components:
  - name: pose_tree
    type: nvidia::isaac::PoseTree
  - type: nvidia::isaac::PoseTreeSetup
    parameters:
      pose_tree: global_pose_tree/pose_tree
  - name: world_frame
    type: nvidia::isaac::PoseTreeFrame
    parameters:
      pose_tree: global_pose_tree/pose_tree
  - name: map_frame
    type: nvidia::isaac::PoseTreeFrame
    parameters:
      pose_tree: global_pose_tree/pose_tree
      parent_frame: global_pose_tree/world_frame
      initial_pose:
        translation: [0.0, 0.0, 0.0]
        rotation_rpy: [0.0, 0.0, 0.0]
  - name: robot_frame
    type: nvidia::isaac::PoseTreeFrame
    parameters:
      pose_tree: global_pose_tree/pose_tree
      parent_frame: global_pose_tree/world_frame
      initial_pose:
        translation: [0.0, 0.0, 0.0]
        rotation_rpy: [0.0, 0.0, 0.0]
